### ISSUE TITLE
[bug] ...Launcher crashes immediately when opened

### ISSUE THREAD

**Issue by Say0rnis** [CreatorsTF/Creators.TF-Community-Launcher#64]
### Prerequisites

- [X] This is not a feature request.
- [X] I checked recent issues and verified that this is not a duplicate.

### UI or mechanical bug?

Mechanical bug, I assume

### Describe the bug

The launcher immediately crashes every time I try to open it, not sure why. A blank gray window that I assume is supposed to be the launcher pops up alongside an error message. Closing either window or pressing "OK" on the error message causes the launcher to close again. I've tried reinstalling, running as administrator, disabling my antivirus, and restarting my computer. Nothing has worked so far.

### Was there an error dialogue for this bug? If so, please, provide its contents here. (optional)

TypeError [ERR_INVALID_ARG_TYPE]: the "path" argument must be of type string. Received undefined
If this error persists, please report it to our GitHub page by making a new 'Issue'.
Visit creators.tf/launcher for more info.
You can also report if via our discord

### Steps to reproduce the behavior

1. Install launcher
2. Attempt to launch "Creators.tf Launcher.exe"
3. Error occurs

### Expected behavior

Launcher loads & functions to launch TF2

### Actual behavior

Launcher does not load & immediately crashes.

### Screenshots (optional)

![Screenshot (52)](https://user-images.githubusercontent.com/85268283/130288838-279f7dc7-6e60-484c-b98d-1403dadfa130.png)

### Operating system and version

Windows 8

### Additional context (optional)

Apologies that this is a bit vague, I genuinely have no idea what's going on here

**Comment by jota11** [comment]
A fix for this bug is available on the [0.2.7](https://github.com/CreatorsTF/Creators.TF-Community-Launcher/releases/tag/0.2.7) release.
