### ISSUE TITLE
[bug] Installed mod version shows 'undefined'

### ISSUE THREAD

**Issue by Retr0-01** [CreatorsTF/Creators.TF-Community-Launcher#69]
### Prerequisites

- [X] This is not a feature request.
- [X] I checked recent issues and verified that this is not a duplicate.

### UI or mechanical bug?

UI

### Describe the bug

As the title says, the 'Mod version' at the top corner of a installed mod shows 'undefined'

### Steps to reproduce the behavior

1. Update launcher to latest version
2. Open it

### Expected behavior

Mod version number should be shown

### Actual behavior

'Undefined' is shown

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/61121754/133302693-1833009e-91f8-42ed-b4eb-c7cbc7b77239.png)

### Operating system and version

Windows 10

**Comment by jota11** [comment]
The only solution is to reinstall the mod.
